---
- name: Set distribution
  set_fact:
    packages_os_distro: "{{ ansible_distribution + '_' + ansible_distribution_major_version | string }}"

- name: Set distribution version for Amazon linux 1
  set_fact:
    packages_os_distro: "{{ ansible_distribution + '_' + '1' }}"
  when: ansible_distribution == "Amazon" and ansible_distribution_version == "NA"

- name: Set distribution version for Ubuntu
  set_fact:
    packages_os_distro: "{{ ansible_distribution + '_' + ansible_distribution_version }}"
  when: ansible_distribution == "Ubuntu"

- name: Merge package groups
  set_fact:
    packages_os_merged: >
      {{
        packages_os['all'] | default({}) |
        combine(packages_os[packages_os_distro | lower] | default({}), recursive=True)
      }}
