---
- name: Converge
  hosts: all
  vars:
    packages_os:
      all:
        vim: present
        wget: present
        man: present
        rsyslog: present
      centos_6:
        iptables: present
        curl: present
      centos_7:
        dos2unix: present
        perl: present
        strace: present
        tcpdump: present
        tmux: present
      amazon_1:
        telnet: present
      amazon_2:
        zsh: present
      ubuntu_18.04:
        apt-file: present
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
